### ISSUE TITLE
Automatically run post-install?

### ISSUE THREAD

**Issue by JamesMGreene** [felixrieseberg/ember-cli-windows-addon#10]
It would be nice if `ember windows` just automatically ran after the module was installed (assuming no ill side effects will occur if it is run more than once).

**Comment by felixrieseberg** [comment]
Hey, I also pushed out a new version. Thanks a lot, those were some great changes!

**Comment by JamesMGreene** [comment]
Welcomed!  Thanks for helping to make developing with modern JS frameworks less painful on Windows.  :gift_heart:

**Comment by felixrieseberg** [comment]
:bow:
